spring:
  application:
    name: web-boss
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:${server.port}
# feign 远程调用失败处理开启  fallback 功能
server:
  port: 8086
feign:
  hystrix:
    enabled: true