spring:
  application:
    name: web-boss
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:8082
server:
  port: 8082
# feign 远程调用失败处理开启  fallback 功能
feign:
  hystrix:
    enabled: true